Cambio nuevo al menu y CSS
juleosanchez/benja pull request #3
Opened 2021-04-24 15:59 UTC by benjavillac

Menu change and CSS sheet

2021-04-28 08:17 UTC, juleosanchez requested changes

2021-04-28 08:17 UTC, juleosanchez commented on aboutus.html
> +  <div id="navigation">
esto deberia ser un `<nav>` Nav es una etiqueta semantica que le da mas sentido o un significado a lo que hay dentro de ella. Solo tienes que cambiar `<div></div>` por `<nav></nav>` aca. _Hacer esto en todos los otros files_.

2021-04-28 08:17 UTC, juleosanchez commented on aboutus.html
> +    <a href="index.html">Start</a> | <a href="aboutus.html">About us</a> | <a href="projects.html">Projects</a> | <a href="events.html">Events</a> | <a href="contact.html">Contact</a> | <a href="dona
Ahora mismo si hago click en el link, me manda a esa pagina. Podrias hacerlo que cuando hago click en algun link, se habra en un nuevo tab? Hat un propiedad del `<a>` llamada **target**. _Hacer esto en todos los otros files._

2021-04-29 09:26 UTC, benjavillac commented on aboutus.html
> +  <div id="navigation">
<div> to <nav> changed

2021-04-29 09:26 UTC, benjavillac commented on aboutus.html
> +    <a href="index.html">Start</a> | <a href="aboutus.html">About us</a> | <a href="projects.html">Projects</a> | <a href="events.html">Events</a> | <a href="contact.html">Contact</a> | <a href="dona
new attribute added for new tab when pressing link

2021-04-29 10:32 UTC, juleosanchez approved these changes

2021-04-29 10:32 UTC, merged